name: Curl to Endpoint

on:
  push:
    branches: [ master ]

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Update package
      run: sudo apt-get update
    - name: Install package
      run: sudo apt-get install curl
    - name: Runngin POST curl to Endpoiny
      run: |
        curl -X POST https://gin-get-repository-name-with-github.onrender.com/ping -H 'Content-Type: application/json' -d "{\"name\": \"$GITHUB_REPOSITORY\"}"
